language: go
go:
  - 1.5
  - 1.6
before_script:
  - curl -L  https://github.com/coreos/etcd/releases/download/v2.3.1/etcd-v2.3.1-linux-amd64.tar.gz -o etcd-v2.3.1-linux-amd64.tar.gz
  - tar xzvf etcd-v2.3.1-linux-amd64.tar.gz
  - ./etcd-v2.3.1-linux-amd64/etcd &
  - go get
  - go get github.com/coreos/go-etcd/etcd
script:
  - go test -tags etcd -race -bench=. ./...
