ignored = [
    "github.com/mholt/caddy",
    "github.com/mholt/caddy/caddyfile",
    "github.com/mholt/caddy/startupshutdown",
    "github.com/miekg/dns",
    "golang.org/x/net/context",
    "golang.org/x/net/context/ctxhttp",
    "golang.org/x/net/http2",
    "golang.org/x/net/http2/hpack",
    "golang.org/x/net/idna",
    "golang.org/x/net/internal/timeseries",
    "golang.org/x/net/lex/httplex",
    "golang.org/x/net/trace",
]

[[constraint]]
    name = "github.com/openzipkin/zipkin-go-opentracing"
    revision = "45e90b00710a4c34a1a7d8a78d90f9b010b0bd4d"
[[override]]
    name = "github.com/apache/thrift"
    revision = "4f77ab8e296d64c57e6ea1c6e3f0f152bc7d6a3a"

[[override]]
    name = "github.com/ugorji/go"
    revision = "8c0409fcbb70099c748d71f714529204975f6c3f"

# client-go 4.0.0 uses apimachinery 1fd2e63a9a370677308a42f24fd40c86438afddf (see Godep.json)
[[constraint]]
    name = "k8s.io/client-go"
    version = "v4.0.0"
[[override]]
    name = "k8s.io/apimachinery"
    revision = "1fd2e63a9a370677308a42f24fd40c86438afddf"
