name: Go Coverage
on: [pull_request]
permissions:
  contents: read

jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.20.0'
        id: go

      - name: Build
        run: go build -v ./...

      - name: Test With Coverage
        run: |
          go install github.com/fatih/faillint@latest
          for d in request core coremain plugin test; do \
             ( cd $d; go test -coverprofile=cover.out -covermode=atomic -race ./...; [ -f cover.out ] && cat cover.out >> ../coverage.txt ); \
          done

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238
